# Generated by Django 4.1.2 on 2022-10-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.CharField(choices=[('BO', 'Боевик'), ('FA', 'Фантастика'), ('VE', 'Вестерн'), ('GA', 'Гагстерский фильм'), ('DE', 'Детектив'), ('DR', 'Драма'), ('HI', 'Исторический фильм'), ('CO', 'Комедия'), ('ME', 'Мелодрама'), ('MU', 'Музакальный фильм'), ('PO', 'Политический фильм'), ('PR', 'Приключенческий фильм'), ('SK', 'Сказка'), ('TR', 'Трагедия'), ('TC', 'Трагикомедия'), ('NN', '--')], default='NN', max_length=2),
        ),
    ]
