# Generated by Django 4.1.2 on 2022-10-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_books', '0002_alter_author_last_name_alter_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.CharField(choices=[('BO', 'Боевик'), ('FA', 'Фантастика'), ('DE', 'Детектив'), ('LR', 'Любовный роман'), ('PR', 'Приключения'), ('TR', 'Триллер'), ('HR', 'Исторический роман'), ('MI', 'Мистика'), ('DR', 'Драма'), ('UG', 'Ужасы'), ('SK', 'Сказка'), ('NN', '--')], default='NN', max_length=2),
        ),
    ]
