# Generated by Django 4.1.2 on 2022-10-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_comment_coment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='coment',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment'),
        ),
    ]
