# Generated by Django 4.1.2 on 2022-10-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_liketocomment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liketoarticle',
            unique_together={('article', 'writer')},
        ),
    ]
