# Generated by Django 4.1.2 on 2022-10-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_liketoarticle_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liketoarticle',
            unique_together={('like_choice', 'article', 'writer')},
        ),
        migrations.AlterUniqueTogether(
            name='liketocomment',
            unique_together={('like_choice', 'comment', 'writer')},
        ),
    ]
