# Generated by Django 4.1.2 on 2022-10-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_liketoarticle_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liketoarticle',
            unique_together={('article', 'writer')},
        ),
        migrations.AlterUniqueTogether(
            name='liketocomment',
            unique_together={('comment', 'writer')},
        ),
    ]
