# Generated by Django 4.1.2 on 2022-10-27 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=1)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=1)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('year_of_public', models.DateField()),
                ('genres', models.CharField(choices=[('BO', 'Боевик'), ('FA', 'Фантастика'), ('DE', 'Детектив'), ('LR', 'Любовный роман'), ('PR', 'Приключения'), ('TR', 'Триллер'), ('HR', 'Исторический роман'), ('MI', 'Мистика'), ('DR', 'Драма'), ('UG', 'Ужасы'), ('SK', 'Сказка'), ('NN', '--')], default='NN', max_length=2)),
                ('availability', models.BooleanField(default=True)),
                ('author', models.ManyToManyField(to='myapp.author')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
